version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${PORT:-8501}:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - my_app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PROMPTFLOW_ENDPOINT=${PROMPTFLOW_ENDPOINT}
      - PROMPTFLOW_KEY=${PROMPTFLOW_KEY}
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge