services:
  - type: web
    name: sacr-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8501
      - key: BACKEND_URL
        fromService:
          name: sacr-backend
          type: web
          property: host

  - type: web
    name: sacr-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PROMPTFLOW_ENDPOINT
        sync: false
      - key: PROMPTFLOW_KEY
        sync: false
