services:
  - type: web
    name: sacr-frontend
    env: docker
    region: oregon
    plan: free
    context: ./frontend
    dockerfile: ./frontend/Dockerfile
    envVars:
      - key: PORT
        value: 8501
      - key: BACKEND_URL
        fromService:
          name: sacr-backend
          type: web
          property: host

  - type: web
    name: sacr-backend
    env: docker
    region: oregon
    plan: free
    context: ./backend
    dockerfile: ./backend/Dockerfile
    envVars:
      - key: PROMPTFLOW_ENDPOINT
        value: "https://sacr-project-sacr-final.eastus2.inference.ml.azure.com/score"
      - key: PROMPTFLOW_KEY
        sync: false
